#!/bin/sh

#
# Sshd Autodiscovery - Allow Password
# ===================================
#
# This script sets whether passwords are allowed.

set -e
umask 0007


#
# Set Allow Password
# ------------------

logger -t "${0}" "Notice: Setting PasswordAuthentication on sshd service..."

if test -f /etc/device/services/sshd/password-authentication.polar; then

  augtool --load-file=/etc/ssh/sshd_config <<-EOF | /usr/bin/logger -t "{0}"
set /files/etc/ssh/sshd_config/PasswordAuthentication yes
save
EOF

else

  augtool --load-file=/etc/ssh/sshd_config <<-EOF | /usr/bin/logger -t "{0}"
set /files/etc/ssh/sshd_config/PasswordAuthentication no
save
EOF

fi

