#!/bin/sh

set -e
umask 0002

if [ "$1" == "--" ]; then

  /usr/bin/sudo /usr/bin/systemctl --quiet enable sshd.service

  if test ! -f "disabled.bin"; then
    echo "sshd is already enabled."
  else
    /usr/libexec/device-tool --lock /etc/device/services/sshd/ --polar disabled -- "disabled" "no"
    if systemctl is-active --quiet sshd-autodiscovery.service; then
      /usr/bin/sudo /usr/bin/systemctl restart sshd-autodiscovery.service
      /usr/bin/sudo /usr/bin/systemctl restart sshd.service
    else
      echo "sshd will be enabled on next reboot."
    fi
  fi

fi

